using Avalonia.Headless.XUnit;
using Avalonia.Platform;
using Xunit;

namespace ObjectStorageClient.App.Tests;

/// <summary>
/// <c>MainWindow.axaml</c> sets <c>Icon="/Assets/appicon.png"</c>, and a missing or renamed asset
/// still compiles — Avalonia only resolves the path when the window is constructed, so the app
/// would build cleanly and then throw on the first launch. No test builds
/// <see cref="Views.MainWindow"/> (it needs the whole DI graph), which leaves this the cheapest
/// place to pin the asset down.
/// </summary>
/// <remarks>
/// Keep the URI here in step with the path in <c>MainWindow.axaml</c>. The asset itself is
/// generated by <c>build/generate-icon.py</c> and committed.
/// </remarks>
public sealed class AppIconTests
{
    private static readonly Uri IconUri = new("avares://ObjectStorageClient.App/Assets/appicon.png");

    private static readonly byte[] PngSignature = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];

    [AvaloniaFact]
    public void WindowIcon_IsPackagedWithTheApplication()
    {
        Assert.True(AssetLoader.Exists(IconUri), $"{IconUri} is not packaged as an Avalonia resource");
    }

    /// <summary>
    /// Decoding is left to the platform, so this only checks the bytes really are a PNG — enough
    /// to catch a placeholder or a truncated file being committed in the asset's place.
    /// </summary>
    [AvaloniaFact]
    public void WindowIcon_IsAPngFile()
    {
        using Stream stream = AssetLoader.Open(IconUri);
        byte[] header = new byte[PngSignature.Length];
        stream.ReadExactly(header);

        Assert.Equal(PngSignature, header);
    }
}
