<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ObjectStorageClient.Core</RootNamespace>
    <AssemblyName>ObjectStorageClient.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ObjectStorageClient.Core.Tests" />
  </ItemGroup>

</Project>
